include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 120

linter:
  rules:
    lines_longer_than_80_chars: false
    require_trailing_commas: false
analyzer:
  errors:
    missing_return: error
    missing_required_param: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"