name: dcc_toolkit
description: "Internal toolkit package used by the DCC team."
version: 0.0.5
homepage: https://dutchcodingcompany.com
repository: https://github.com/DutchCodingCompany/dcc_toolkit

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  chopper: ^8.0.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.2.1
  mocktail: ^1.0.3
  parameterized_test: ^2.0.0
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true

